/*
  accounts.js
  Final optimized replacement version.

  Replace your old accounts.js with this file.

  Browser usage:
    window.ACCOUNTS_DATA
    window.accounts

  Legacy safety:
    ACCOUNTS_B64 is kept as null so old references do not crash immediately.
    New storefront data is in ACCOUNTS_DATA.accounts.
*/

const ACCOUNTS_B64 = null;

const ACCOUNTS_DATA = {
  "meta": {
    "version": "optimized-view-v1-final-js",
    "accountCount": 35,
    "description": "Optimized storefront JSON with display titles, summaries, tags, normalized status, normalized price, and parsed numeric fields.",
    "replaces": "old ACCOUNTS_B64 Base64 HTML table format"
  },
  "accounts": [
    {
      "id": 1,
      "discord_id": null,
      "level": "25 - OW2",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🟢OG Account (2022)<br>🔓SMS Verified • Warranty<br>⭐Endorsement Level 2<br>✨OW1 Atlanta Reign Soldier: 76, Polar Brig",
      "weapons": "",
      "balance": "",
      "rank": "Reset (S1 2026)<br>Plat Below",
      "nameChange": "✘",
      "screenshot": "https://imgur.com/a/pJ5HYrs",
      "price": "$10.7",
      "title": "2022 · OW1 Account · $10.7",
      "summary": "OW1 Account. Reset (S1 2026) Plat Below.",
      "accountType": "OW1 Account",
      "year": "2022",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 10.7,
      "priceType": "fixed",
      "nameChangeAvailable": false,
      "mythicPrisms": null,
      "credits": null,
      "competitivePoints": null,
      "rareSkins": [],
      "tags": [
        "OW1",
        "OW2",
        "2022",
        "In Stock"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 2,
      "discord_id": null,
      "level": "32 - OW2",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🟢OG Account (2023)<br>🔓SMS Verified • Warranty<br>⭐Endorsement Level 2<br>✨OWL Bap, Vancouver Titan Brig, Infinite Ace DVa, Quicksilver Sombra",
      "weapons": "",
      "balance": "",
      "rank": "Fresh Rank Ready",
      "nameChange": "✓",
      "screenshot": "https://imgur.com/a/RWCWORA",
      "price": "$12.7",
      "title": "2023 · OW2 OG Account · Rank Ready · $12.7",
      "summary": "OW2 OG Account. featured skins: OWL. Fresh Rank Ready.",
      "accountType": "OW2 OG Account",
      "year": "2023",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 12.7,
      "priceType": "fixed",
      "nameChangeAvailable": true,
      "mythicPrisms": null,
      "credits": null,
      "competitivePoints": null,
      "rareSkins": [
        "OWL"
      ],
      "tags": [
        "OW2",
        "2023",
        "In Stock",
        "Rank Ready",
        "Name Change Available",
        "League Skins"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 3,
      "discord_id": null,
      "level": "115 - OW2",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🟢OG Account (2024)<br>🔓SMS Verified • Warranty<br>⭐Endorsement Level 2<br>✨Biohazard Ram, Grill Zombie: 76",
      "weapons": "Golden: Soldier: 76",
      "balance": "⏱ 38H • 246G<br>🏅1530 Legacy Comp points",
      "rank": "Reset (S1 2026)<br>S13: Gold All Roles",
      "nameChange": "✓",
      "screenshot": "https://imgur.com/a/TkrcWCt",
      "price": "$19.7",
      "title": "2024 · OW2 OG Account · Golden Weapon · $19.7",
      "summary": "OW2 OG Account. Reset (S1 2026) S13: Gold All Roles.",
      "accountType": "OW2 OG Account",
      "year": "2024",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 19.7,
      "priceType": "fixed",
      "nameChangeAvailable": true,
      "mythicPrisms": null,
      "credits": null,
      "competitivePoints": 1530,
      "rareSkins": [],
      "tags": [
        "OW2",
        "2024",
        "In Stock",
        "Golden Weapon",
        "Name Change Available"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 4,
      "discord_id": null,
      "level": "17+32 - OW1",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🏆OG OW1 Origins Edition (2020)<br>⭐Endorsement Level 2 • Cassidy(Lv.15) • DPS Main<br>✨OW1 Chengdu Hunter Rein, Heist Reaper<br>📸Full Skin Details in Screenshot",
      "weapons": "",
      "balance": "⏱ 27H • 224G<br>🪙2850 Credits",
      "rank": "Fresh Rank Ready",
      "nameChange": "✓",
      "screenshot": "https://imgur.com/a/Em5fnpp",
      "price": "$20.7",
      "title": "2020 · OW1 Origins Account · Rank Ready · $20.7",
      "summary": "OW1 Origins Account. 2,850 Credits. featured skins: Chengdu Hunter. Fresh Rank Ready.",
      "accountType": "OW1 Origins Account",
      "year": "2020",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 20.7,
      "priceType": "fixed",
      "nameChangeAvailable": true,
      "mythicPrisms": null,
      "credits": 2850,
      "competitivePoints": null,
      "rareSkins": [
        "Chengdu Hunter"
      ],
      "tags": [
        "OW1",
        "2020",
        "In Stock",
        "Credits",
        "Rank Ready",
        "Name Change Available",
        "DPS Main"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 5,
      "discord_id": null,
      "level": "OW2",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🟢OG Account (2022)<br>🔓SMS Verified • Warranty",
      "weapons": "",
      "balance": "",
      "rank": "Bronze All Roles",
      "nameChange": "✓",
      "screenshot": "https://imgur.com/a/u8RujGu",
      "price": "$20.7",
      "title": "2022 · OW2 OG Account · $20.7",
      "summary": "OW2 OG Account. Bronze All Roles.",
      "accountType": "OW2 OG Account",
      "year": "2022",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 20.7,
      "priceType": "fixed",
      "nameChangeAvailable": true,
      "mythicPrisms": null,
      "credits": null,
      "competitivePoints": null,
      "rareSkins": [],
      "tags": [
        "OW2",
        "2022",
        "In Stock",
        "Name Change Available"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 6,
      "discord_id": null,
      "level": "41 - OW2",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🟢OG Account (2022)<br>🔓SMS Verified • Warranty<br>✨OW1 Boston Uprising Bastion, OW1 FLO Mayhem 2018 Sym, <br>✨Cyberhog, Prideful Rein, KOI Hanzo, Fire Engine Bastion, Divine Monkey Genji, Fenrir Reaper, Eclipse Illari",
      "weapons": "",
      "balance": "",
      "rank": "Reset (S1 2026)<br>Plat Below",
      "nameChange": "✘",
      "screenshot": "https://imgur.com/a/zy2y4fW",
      "price": "$22.7",
      "title": "2018 · OW1 Account · $22.7",
      "summary": "OW1 Account. Hanzo. Reset (S1 2026) Plat Below.",
      "accountType": "OW1 Account",
      "year": "2018",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 22.7,
      "priceType": "fixed",
      "nameChangeAvailable": false,
      "mythicPrisms": null,
      "credits": null,
      "competitivePoints": null,
      "rareSkins": [],
      "tags": [
        "OW1",
        "OW2",
        "2018",
        "In Stock",
        "Hanzo"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 7,
      "discord_id": null,
      "level": "56+11 - OW1",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🏆OG OW1 Origins Edition (2020)<br>⭐Endorsement Level 3 • Soldier:76 • DPS Main<br>✨Atlanta Reign Doom, Instructor Chase Soj<br>📸Full Skin Details in Screenshot",
      "weapons": "",
      "balance": "⏱ 69H • 597G<br>🪙4000 Credits<br>🏅1386 Legacy Comp points",
      "rank": "Reset (S1 2026)<br>Plat Below",
      "nameChange": "✘",
      "screenshot": "https://imgur.com/a/XSAgM63",
      "price": "$22.7",
      "title": "2020 · OW1 Origins Account · $22.7",
      "summary": "OW1 Origins Account. 4,000 Credits. DPS Main. Reset (S1 2026) Plat Below.",
      "accountType": "OW1 Origins Account",
      "year": "2020",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 22.7,
      "priceType": "fixed",
      "nameChangeAvailable": false,
      "mythicPrisms": null,
      "credits": 4000,
      "competitivePoints": 1386,
      "rareSkins": [],
      "tags": [
        "OW1",
        "2020",
        "In Stock",
        "Credits",
        "DPS Main"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 8,
      "discord_id": null,
      "level": "72+10 - OW1",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🏆OG OW1 Origins Edition (2017)<br>⭐Endorsement Level 2 • Sup Main • Pink Mercy Limited ICON<br>🏅OW1 - Season 9 Competitor<br>✨OWCS Cassidy, OW1 LA Valiant 2018 Winston<br>📸Full Skin Details in Screenshot",
      "weapons": "",
      "balance": "⏱ 56H • 464G<br>🪙3115 Credits<br>🏅830 Legacy Comp points",
      "rank": "Reset (S1 2026)<br>Plat Below",
      "nameChange": "✘",
      "screenshot": "https://imgur.com/a/CiJJ51E",
      "price": "$25.7",
      "title": "2017 · OW1 Origins Account · $25.7",
      "summary": "OW1 Origins Account. 3,115 Credits. featured skins: Pink Mercy, OWCS. Reset (S1 2026) Plat Below.",
      "accountType": "OW1 Origins Account",
      "year": "2017",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 25.7,
      "priceType": "fixed",
      "nameChangeAvailable": false,
      "mythicPrisms": null,
      "credits": 3115,
      "competitivePoints": 830,
      "rareSkins": [
        "Pink Mercy",
        "OWCS"
      ],
      "tags": [
        "OW1",
        "2017",
        "In Stock",
        "Credits",
        "League Skins",
        "Support Main"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 9,
      "discord_id": null,
      "level": "77+5 - OW1",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🏆OG OW1 Origins Edition (2017)<br>⭐Endorsement Level 2 • DPS Main<br>✨Dallas Fuel Junk, OWL Brig<br>📸Full Skin Details in Screenshot",
      "weapons": "",
      "balance": "⏱ 85H • 767G<br>🪙8980 Credits<br>🏅1980 Legacy Comp points",
      "rank": "Reset (S1 2026)<br>Plat Below",
      "nameChange": "✓",
      "screenshot": "https://imgur.com/a/Cv3Vpyy",
      "price": "$25.7",
      "title": "2017 · OW1 Origins Account · $25.7",
      "summary": "OW1 Origins Account. 8,980 Credits. featured skins: OWL, Dallas Fuel. Reset (S1 2026) Plat Below.",
      "accountType": "OW1 Origins Account",
      "year": "2017",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 25.7,
      "priceType": "fixed",
      "nameChangeAvailable": true,
      "mythicPrisms": null,
      "credits": 8980,
      "competitivePoints": 1980,
      "rareSkins": [
        "OWL",
        "Dallas Fuel"
      ],
      "tags": [
        "OW1",
        "2017",
        "In Stock",
        "Credits",
        "Name Change Available",
        "League Skins",
        "DPS Main"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 10,
      "discord_id": null,
      "level": "OW2",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🟢OG Account (2022)<br>🔓SMS Verified • Warranty<br>🎮Premium Battle Pass (Season 2, 3) - Zeus<br>✨Invisiable Man Cassidy, Honey Bee Mercy",
      "weapons": "",
      "balance": "⏱ 109H • 784G<br>🪙2050 Credits",
      "rank": "Reset",
      "nameChange": "✓",
      "screenshot": "https://imgur.com/a/Wy9aRDG",
      "price": "$25.7",
      "title": "2022 · OW2 OG Account · $25.7",
      "summary": "OW2 OG Account. 2,050 Credits. featured skins: Zeus. Reset.",
      "accountType": "OW2 OG Account",
      "year": "2022",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 25.7,
      "priceType": "fixed",
      "nameChangeAvailable": true,
      "mythicPrisms": null,
      "credits": 2050,
      "competitivePoints": null,
      "rareSkins": [
        "Zeus"
      ],
      "tags": [
        "OW2",
        "2022",
        "In Stock",
        "Credits",
        "Name Change Available",
        "Battle Pass"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 11,
      "discord_id": null,
      "level": "104 - OW2",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🟢OG Account (2023)<br>🔓SMS Verified • Warranty<br>⭐Genji(Lv.25) • DPS Main<br>🎮Premium Battle Pass: Season 2026-S2 + 80 Mythic Prisms<br>✨LA Gladiators Zen, Infinite Guard: 76, Cozy Ashe, Cupid Hanzo, Bounty Hunter Bap",
      "weapons": "",
      "balance": "⏱ 106H • 411G<br>💎80 Mythic Prisms<br>🪙2175 Credits<br>🏅350 Legacy Comp points",
      "rank": "Reset (S1 2026)",
      "nameChange": "✓",
      "screenshot": "https://imgur.com/a/hW3hbBS",
      "price": "$26.7",
      "title": "2023 · OW2 OG Account · 80 Mythic Prisms · $26.7",
      "summary": "OW2 OG Account. 80 Mythic Prisms. 2,175 Credits. featured skins: LA Gladiators. Reset (S1 2026).",
      "accountType": "OW2 OG Account",
      "year": "2023",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 26.7,
      "priceType": "fixed",
      "nameChangeAvailable": true,
      "mythicPrisms": 80,
      "credits": 2175,
      "competitivePoints": 350,
      "rareSkins": [
        "LA Gladiators"
      ],
      "tags": [
        "OW2",
        "2023",
        "In Stock",
        "Mythic Prisms",
        "Credits",
        "Name Change Available",
        "Battle Pass",
        "DPS Main",
        "Hanzo"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 12,
      "discord_id": null,
      "level": "33+24 - OW1",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🏆OG OW1 Origins Edition (2021)<br>⭐Endorsement Level 3 • DPS Main<br>✨GZ Charge Junk<br>📸Full Skin Details in Screenshot",
      "weapons": "",
      "balance": "⏱ 89H • 651G<br>🪙4475 Credits<br>🏅1980 Legacy Comp points",
      "rank": "Reset<br>Bronze5 MMR All Roles",
      "nameChange": "✓",
      "screenshot": "https://imgur.com/a/0a7NnK4",
      "price": "$28.7",
      "title": "2021 · OW1 Origins Account · $28.7",
      "summary": "OW1 Origins Account. 4,475 Credits. DPS Main. Reset Bronze5 MMR All Roles.",
      "accountType": "OW1 Origins Account",
      "year": "2021",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 28.7,
      "priceType": "fixed",
      "nameChangeAvailable": true,
      "mythicPrisms": null,
      "credits": 4475,
      "competitivePoints": 1980,
      "rareSkins": [],
      "tags": [
        "OW1",
        "2021",
        "In Stock",
        "Credits",
        "Name Change Available",
        "DPS Main"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 13,
      "discord_id": null,
      "level": "81+25 - OW1",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🏆OG OW1 Origins Edition (2017)<br>🏅OW1 - Season 4 Competitor • Soldier • DPS Main<br>🎮Premium Battle Pass Season 1 - Incompleted<br>✨Dallas Fuel Mercy",
      "weapons": "",
      "balance": "⏱ 80H • 553G<br>🪙3225 Credits<br>🏅2763 Legacy Comp points",
      "rank": "Reset",
      "nameChange": "✓",
      "screenshot": "https://imgur.com/a/y29OL7V",
      "price": "$28.7",
      "title": "2017 · OW1 Origins Account · $28.7",
      "summary": "OW1 Origins Account. 3,225 Credits. featured skins: Dallas Fuel. Reset.",
      "accountType": "OW1 Origins Account",
      "year": "2017",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 28.7,
      "priceType": "fixed",
      "nameChangeAvailable": true,
      "mythicPrisms": null,
      "credits": 3225,
      "competitivePoints": 2763,
      "rareSkins": [
        "Dallas Fuel"
      ],
      "tags": [
        "OW1",
        "2017",
        "In Stock",
        "Credits",
        "Name Change Available",
        "Battle Pass",
        "DPS Main"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 14,
      "discord_id": null,
      "level": "85 - OW1",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🏆OG OW1 Origins Edition (2016)<br>⭐Endorsement Level 3 • Sup Main<br>✨OW1 FLO Mayhem Hog, <br>✨Comic Book, Nano D.VA",
      "weapons": "",
      "balance": "⏱ 49H • 432G<br>🪙5750 Credits",
      "rank": "Fresh Rank Ready",
      "nameChange": "✓",
      "screenshot": "https://imgur.com/a/w15An3J",
      "price": "$29.7",
      "title": "2016 · OW1 Origins Account · Rank Ready · $29.7",
      "summary": "OW1 Origins Account. 5,750 Credits. Support Main. Fresh Rank Ready.",
      "accountType": "OW1 Origins Account",
      "year": "2016",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 29.7,
      "priceType": "fixed",
      "nameChangeAvailable": true,
      "mythicPrisms": null,
      "credits": 5750,
      "competitivePoints": null,
      "rareSkins": [],
      "tags": [
        "OW1",
        "2016",
        "In Stock",
        "Credits",
        "Rank Ready",
        "Name Change Available",
        "Support Main"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 15,
      "discord_id": null,
      "level": "28 - OW2",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🟢OG Account (2022)<br>🔓SMS Verified • Warranty<br>⭐Endorsement Level 3<br>🎮Premium Battle Pass (Season 3, 4, 2026-S1) - Amaterasu + 80 Mythic Prisms<br>✨GZ Charge Ana<br>✨Infinite Ace D.Va, Invisible man, Honey Bee Mercy",
      "weapons": "",
      "balance": "⏱ 123H • 491G<br>💎80 Mythic Prisms<br>🪙2400 Credits<br>🏅835 Legacy Comp points",
      "rank": "Reset (S1 2026)<br>S20: Plat 2 Tank | Bronze 1 DPS",
      "nameChange": "✘",
      "screenshot": "https://imgur.com/a/dZPXnHt",
      "price": "$35.7",
      "title": "2022 · OW2 OG Account · 80 Mythic Prisms · $35.7",
      "summary": "OW2 OG Account. 80 Mythic Prisms. 2,400 Credits. featured skins: Amaterasu. Reset (S1 2026) S20: Plat 2 Tank | Bronze 1 DPS.",
      "accountType": "OW2 OG Account",
      "year": "2022",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 35.7,
      "priceType": "fixed",
      "nameChangeAvailable": false,
      "mythicPrisms": 80,
      "credits": 2400,
      "competitivePoints": 835,
      "rareSkins": [
        "Amaterasu"
      ],
      "tags": [
        "OW2",
        "2022",
        "In Stock",
        "Mythic Prisms",
        "Credits",
        "Battle Pass",
        "DPS Main",
        "Tank"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 16,
      "discord_id": null,
      "level": "109 - OW2",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🟢OG Account (2023)<br>🔓SMS Verified • Warranty<br>⭐Endorsement Level 2<br>✨All - Stars Rein, Norse Doom, CD Hunter Sym, Aztec Sombra",
      "weapons": "",
      "balance": "⏱ 33H • 218G<br>🏅1980 Legacy Comp points",
      "rank": "Reset (S1 2026)<br>S11 Silver 2 Tank<br>Stadium Comp Unlock",
      "nameChange": "✓",
      "screenshot": "https://imgur.com/a/QkCyCPw",
      "price": "$35.7",
      "title": "2023 · OW2 OG Account · $35.7",
      "summary": "OW2 OG Account. Tank. Reset (S1 2026) S11 Silver 2 Tank Stadium Comp Unlock.",
      "accountType": "OW2 OG Account",
      "year": "2023",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 35.7,
      "priceType": "fixed",
      "nameChangeAvailable": true,
      "mythicPrisms": null,
      "credits": null,
      "competitivePoints": 1980,
      "rareSkins": [],
      "tags": [
        "OW2",
        "2023",
        "In Stock",
        "Name Change Available",
        "Tank"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 17,
      "discord_id": null,
      "level": "35+3 - OW1",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🏆OG OW1 (2021)<br>✨Crmson Summer Genji<br>✨CD Hunter Moria<br>📸Full Skin Details in Screenshot",
      "weapons": "",
      "balance": "🪙4150 Credits<br>🏅785 Legacy Comp points",
      "rank": "Reset (S1 2026)",
      "nameChange": "✘",
      "screenshot": "https://imgur.com/a/t7m9J6c",
      "price": "$35.7",
      "title": "2021 · OW1 Account · $35.7",
      "summary": "OW1 Account. 4,150 Credits. Reset (S1 2026).",
      "accountType": "OW1 Account",
      "year": "2021",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 35.7,
      "priceType": "fixed",
      "nameChangeAvailable": false,
      "mythicPrisms": null,
      "credits": 4150,
      "competitivePoints": 785,
      "rareSkins": [],
      "tags": [
        "OW1",
        "2021",
        "In Stock",
        "Credits"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 18,
      "discord_id": null,
      "level": "87 - OW1",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🏆OG OW1 Origins Edition (2016)<br>🏅OW1 - Season 1 Competitor • DPS Main<br>✨Noire Widowmaker, Flo Mayhem Bap",
      "weapons": "",
      "balance": "⏱ 82H • 608G<br>🪙4599 Credits<br>🏅2338 Legacy Comp points",
      "rank": "Reset",
      "nameChange": "✘",
      "screenshot": "https://imgur.com/a/KGLSLgM",
      "price": "$36.7",
      "title": "2016 · OW1 Origins Account · $36.7",
      "summary": "OW1 Origins Account. 4,599 Credits. featured skins: Noire Widow. Reset.",
      "accountType": "OW1 Origins Account",
      "year": "2016",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 36.7,
      "priceType": "fixed",
      "nameChangeAvailable": false,
      "mythicPrisms": null,
      "credits": 4599,
      "competitivePoints": 2338,
      "rareSkins": [
        "Noire Widow"
      ],
      "tags": [
        "OW1",
        "2016",
        "In Stock",
        "Credits",
        "DPS Main",
        "Widow"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 19,
      "discord_id": null,
      "level": "OW2",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🟢OG Account (2022)<br>🔓SMS Verified • Warranty<br>✨OW1 League White/Gray: DVA, Ball, Ashe, Bastion, Genji, Hanzo, Mei, Tracer, Ana, Brig, Mercy, Zen<br>✨OW1 SFS Bap, LA Gladiators Moira",
      "weapons": "",
      "balance": "",
      "rank": "Reset (S1 2026)<br>Gold Below",
      "nameChange": "✓",
      "screenshot": "📸 View Skins",
      "price": "$38.9",
      "title": "2022 · OW1 Account · $38.9",
      "summary": "OW1 Account. featured skins: LA Gladiators. Reset (S1 2026) Gold Below.",
      "accountType": "OW1 Account",
      "year": "2022",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 38.9,
      "priceType": "fixed",
      "nameChangeAvailable": true,
      "mythicPrisms": null,
      "credits": null,
      "competitivePoints": null,
      "rareSkins": [
        "LA Gladiators"
      ],
      "tags": [
        "OW1",
        "OW2",
        "2022",
        "In Stock",
        "Name Change Available",
        "League Skins",
        "Hanzo"
      ],
      "screenshotStatus": "missing_or_invalid"
    },
    {
      "id": 20,
      "discord_id": null,
      "level": "107 - OW1",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🏆OG OW1 Origins Edition (2017)<br>⭐Endorsement Level 2<br>🏅OW1 - Season 7 Competitor • Never Played OW2<br>✨OW1 Team Skin: NY Excelsiors Soldier: 76, GZ Charges Hanzo<br>📸Full Skin Details in Screenshot",
      "weapons": "Golden: Soldier 76",
      "balance": "⏱ 95H • 587G<br>🪙5080 Credits<br>🏅805 Legacy Comp points",
      "rank": "Reset (S1 2026)",
      "nameChange": "✘",
      "screenshot": "📸 View Skins",
      "price": "$39.9",
      "title": "2017 · OW1 Origins Account · Golden Weapon · $39.9",
      "summary": "OW1 Origins Account. 5,080 Credits. featured skins: OW1 Team, NY Excelsior. Reset (S1 2026).",
      "accountType": "OW1 Origins Account",
      "year": "2017",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 39.9,
      "priceType": "fixed",
      "nameChangeAvailable": false,
      "mythicPrisms": null,
      "credits": 5080,
      "competitivePoints": 805,
      "rareSkins": [
        "OW1 Team",
        "NY Excelsior"
      ],
      "tags": [
        "OW1",
        "OW2",
        "2017",
        "In Stock",
        "Credits",
        "Golden Weapon",
        "Hanzo"
      ],
      "screenshotStatus": "missing_or_invalid"
    },
    {
      "id": 21,
      "discord_id": null,
      "level": "95 - OW1",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🏆OG OW1 Origins Edition (2019)<br>⭐Endorsement Level 3 • DPS Main • Never Played OW2<br>✨Huston Outlaws Doom • OW1 Legendary skins collected<br>📸Full Skin Details in Screenshot",
      "weapons": "",
      "balance": "⏱ 92H • 725G<br>🪙5375 Credits<br>🏅615 Legacy Comp points",
      "rank": "Reset<br>Never Played OW2",
      "nameChange": "✓",
      "screenshot": "https://imgur.com/a/i2g0ZnN",
      "price": "$42.7",
      "title": "2019 · OW1 Origins Account · $42.7",
      "summary": "OW1 Origins Account. 5,375 Credits. DPS Main. Reset Never Played OW2.",
      "accountType": "OW1 Origins Account",
      "year": "2019",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 42.7,
      "priceType": "fixed",
      "nameChangeAvailable": true,
      "mythicPrisms": null,
      "credits": 5375,
      "competitivePoints": 615,
      "rareSkins": [],
      "tags": [
        "OW1",
        "OW2",
        "2019",
        "In Stock",
        "Credits",
        "Name Change Available",
        "DPS Main"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 22,
      "discord_id": null,
      "level": "34 - OW2",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🟢OG Account (2023)  <br>🔓SMS Verified • Warranty<br>⭐Endorsement Level 2 • High MMR All Roles<br>✨OWCS Winston",
      "weapons": "",
      "balance": "",
      "rank": "2026-S1: Diamond 3 - Master 5 Tank<br>Gold 2 - Diamond 2 DPS<br>GM4 Support",
      "nameChange": "✓",
      "screenshot": "https://imgur.com/a/P3MR0kn",
      "price": "$48.7",
      "title": "2023 · OW2 OG Account · $48.7",
      "summary": "OW2 OG Account. featured skins: OWCS. 2026-S1: Diamond 3 - Master 5 Tank Gold 2 - Diamond 2 DPS GM4 Support.",
      "accountType": "OW2 OG Account",
      "year": "2023",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 48.7,
      "priceType": "fixed",
      "nameChangeAvailable": true,
      "mythicPrisms": null,
      "credits": null,
      "competitivePoints": null,
      "rareSkins": [
        "OWCS"
      ],
      "tags": [
        "OW2",
        "2023",
        "In Stock",
        "Name Change Available",
        "League Skins",
        "DPS Main",
        "Support Main",
        "Tank"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 23,
      "discord_id": null,
      "level": "7+74 - OW1",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🏆OG OW1 Origins Edition (2020)<br>⭐Endorsement Level 4 <br>✨Executioner JQ, Medusa Widow, OW2 Conterders Genji, Guangmu Taiwang/Divinator/Visual Kei Kiriko, Pearlescent Brig, <br>📸Full Skin Details in Screenshot",
      "weapons": "",
      "balance": "⏱ 137 H • 858G<br>🪙3525 Credits<br>🏅2307 Legacy Comp points",
      "rank": "Reset (S1 2026)<br>Stadium Comp Unlock",
      "nameChange": "✓",
      "screenshot": "https://imgur.com/a/hj2msAY",
      "price": "$49.7",
      "title": "2020 · OW1 Origins Account · $49.7",
      "summary": "OW1 Origins Account. 3,525 Credits. Widow. Reset (S1 2026) Stadium Comp Unlock.",
      "accountType": "OW1 Origins Account",
      "year": "2020",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 49.7,
      "priceType": "fixed",
      "nameChangeAvailable": true,
      "mythicPrisms": null,
      "credits": 3525,
      "competitivePoints": 2307,
      "rareSkins": [],
      "tags": [
        "OW1",
        "OW2",
        "2020",
        "In Stock",
        "Credits",
        "Name Change Available",
        "Widow"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 24,
      "discord_id": null,
      "level": "291 - OW1",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🏆OG OW1 Origins Edition (2017)<br>⭐Endorsement Level 4 • DPS Main • Never Played OW2<br>✨ ShangHai Dragon Junk/Reaper<br>📸 A lot OW1 Limited Skin Collected: Nano DVa, Inferno, Comic Book",
      "weapons": "Golden: Genji",
      "balance": "⏱ 242H • 1675G",
      "rank": "Reset",
      "nameChange": "✓",
      "screenshot": "https://imgur.com/a/IDGkNvS",
      "price": "$55.7",
      "title": "2017 · OW1 Origins Account · Golden Weapon · $55.7",
      "summary": "OW1 Origins Account. featured skins: Shanghai. Reset.",
      "accountType": "OW1 Origins Account",
      "year": "2017",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 55.7,
      "priceType": "fixed",
      "nameChangeAvailable": true,
      "mythicPrisms": null,
      "credits": null,
      "competitivePoints": null,
      "rareSkins": [
        "Shanghai"
      ],
      "tags": [
        "OW1",
        "OW2",
        "2017",
        "In Stock",
        "Golden Weapon",
        "Name Change Available",
        "DPS Main"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 25,
      "discord_id": null,
      "level": "402 - OW1",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🏆OG OW1 Pre-Purchase Edition (2016)<br>⭐Endorsement Level  3 • DPS Main<br>🏅OW1 - Season 2 Competitor • Never Played OW2<br>✨OW1 Seoul Dynasty D.Va, Noire Widow<br>📸Full Skin Details in Screenshot",
      "weapons": "Golden: Rein, Ashe, Genji, Brig",
      "balance": "⏱ 372H • 2221G<br>🪙11730 Credits<br>🏅1023 Legacy Comp points",
      "rank": "Reset",
      "nameChange": "✓",
      "screenshot": "https://imgur.com/a/qyYUruX",
      "price": "$58.7",
      "title": "2016 · OW1 Pre-Purchase Account · Golden Weapon · $58.7",
      "summary": "OW1 Pre-Purchase Account. 11,730 Credits. featured skins: Noire Widow, Seoul Dynasty. Reset.",
      "accountType": "OW1 Pre-Purchase Account",
      "year": "2016",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 58.7,
      "priceType": "fixed",
      "nameChangeAvailable": true,
      "mythicPrisms": null,
      "credits": 11730,
      "competitivePoints": 1023,
      "rareSkins": [
        "Noire Widow",
        "Seoul Dynasty"
      ],
      "tags": [
        "OW1",
        "OW2",
        "2016",
        "In Stock",
        "Credits",
        "Golden Weapon",
        "Name Change Available",
        "DPS Main",
        "Widow"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 26,
      "discord_id": null,
      "level": "104 - OW2",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🟢OG Account (2022)<br>🔓SMS Verified • Warranty<br>⭐Endorsement Level 3 • Doom • Tank Main<br>🏆Hide My Name • Eligible<br>🎮Premium Battle Pass: Season 20, 2026-S1 + 160 Mythic Prisms<br>✨GZ Charge Soj, Diamond Magni Torb, Herms Lucio, Cozy Wuyang",
      "weapons": "",
      "balance": "⏱ 285 H • 1563 G<br>💎160 Mythic Prisms<br>🪙7975 Credits<br>🏅1130 Legacy Comp points",
      "rank": "Reset (S1 2026)<br>Stadium Comp Unlock",
      "nameChange": "✘",
      "screenshot": "https://imgur.com/a/U241RLp",
      "price": "$58.7",
      "title": "2022 · OW2 OG Account · 160 Mythic Prisms · $58.7",
      "summary": "OW2 OG Account. 160 Mythic Prisms. 7,975 Credits. Tank. Reset (S1 2026) Stadium Comp Unlock.",
      "accountType": "OW2 OG Account",
      "year": "2022",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 58.7,
      "priceType": "fixed",
      "nameChangeAvailable": false,
      "mythicPrisms": 160,
      "credits": 7975,
      "competitivePoints": 1130,
      "rareSkins": [],
      "tags": [
        "OW2",
        "2022",
        "In Stock",
        "Mythic Prisms",
        "Credits",
        "Battle Pass",
        "Tank"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 27,
      "discord_id": null,
      "level": "297 - OW1",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🏆OG OW1 Origins Edition (2016)<br>⭐Endorsement Level 3 • DPS Main • Never Played OW2<br>🏅OW1 - Season 1, 2, 3 ... Competitor<br>📸 A lot OW1 Limited Skin Collected",
      "weapons": "Golden: Hog, Cassidy, Bap + 1 Any Gold/Jade/Galactic Weapon Skin",
      "balance": "⏱ 295H • 1514G<br>🪙15205 Credits<br>🏅4085 Legacy Comp points",
      "rank": "Reset",
      "nameChange": "✓",
      "screenshot": "https://imgur.com/a/yplbvFU",
      "price": "$65.7",
      "title": "2016 · OW1 Origins Account · Golden Weapon · $65.7",
      "summary": "OW1 Origins Account. 15,205 Credits. DPS Main. Reset.",
      "accountType": "OW1 Origins Account",
      "year": "2016",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 65.7,
      "priceType": "fixed",
      "nameChangeAvailable": true,
      "mythicPrisms": null,
      "credits": 15205,
      "competitivePoints": 4085,
      "rareSkins": [],
      "tags": [
        "OW1",
        "OW2",
        "2016",
        "In Stock",
        "Credits",
        "Golden Weapon",
        "Jade Weapon",
        "Galactic Weapon",
        "Name Change Available",
        "DPS Main"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 28,
      "discord_id": null,
      "level": "568+73 - OW1",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🏆OG OW1 (2016) • OW1 Stacked<br>⭐Endorsement Level 3 <br>🏅OW1 - Season 2 Competitor • DPS Main<br>🏆Top 500 Eligible: 228/250<br>🎮Premium Battle Pass 2026-S1 - 80 Mythic Prisms<br>⭐SFS Orisa, OW1 SH Dragon Hog, Heist Hog, Rugby JQ, Beach Rescue/Wyvern Mercy, <br>📸Full Skin Details in Screenshot",
      "weapons": "Golden: Zarya, Torb, Widow, Kiriko, Mercy +1 Any Gold/Jade/Galactic Weapon Skin",
      "balance": "⏱ 673H • 4036G<br>💎80 Mythic Prisms<br>🪙9595 Credits<br>🏅2082 Legacy Comp Points • 1315 Comp Points",
      "rank": "Plat 1 Tank | Plat 4 Sup",
      "nameChange": "✘",
      "screenshot": "https://imgur.com/a/FlOMpES",
      "price": "$128.7",
      "title": "2016 · OW1 Stack Account · 80 Mythic Prisms · $128.7",
      "summary": "OW1 Stack Account. 80 Mythic Prisms. 9,595 Credits. DPS Main, Tank, Widow. Plat 1 Tank | Plat 4 Sup.",
      "accountType": "OW1 Stack Account",
      "year": "2016",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 128.7,
      "priceType": "fixed",
      "nameChangeAvailable": false,
      "mythicPrisms": 80,
      "credits": 9595,
      "competitivePoints": 1315,
      "rareSkins": [],
      "tags": [
        "OW1",
        "2016",
        "In Stock",
        "Mythic Prisms",
        "Credits",
        "Top 500",
        "Golden Weapon",
        "Jade Weapon",
        "Galactic Weapon",
        "Battle Pass",
        "DPS Main",
        "Tank",
        "Widow"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 29,
      "discord_id": null,
      "level": "554 - OW2",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🟢OG Account (2023)<br>🔓SMS Verified • Warranty<br>⭐Endorsement Level 4 • Pharah/Junk • DPS Main<br>🏆Hide My Name • Eligible <br>🎮Premium Battle Pass (Season 11, 13, 15, 20) - Calamity Empress(Iridescent), Cyber Fuel, Ultraviolet Sentinel<br>✨Retro Future/Carved Orisa, Kaiju/Cyclops Hog, Talon Zarya, Heavy Metal JQ, Lich King Rein, Flower Child Mei, Heart Of Grace Widow, Archangle Pharah, Loki/Aztec Sombra, Cybermonk Zen, Cardboard Brig, Poolside Illari<br>✨Seoul Dynasty Junk",
      "weapons": "Nerf Gelfire Pro Tracer Weapon",
      "balance": "⏱ 303H • 2161G<br>🪙1380 Coins<br>🏅1845 Legacy Comp points",
      "rank": "Gold3 Sup",
      "nameChange": "✓",
      "screenshot": "https://imgur.com/a/LW8SRoO",
      "price": "$138.7",
      "title": "2023 · OW2 OG Account · $138.7",
      "summary": "OW2 OG Account. featured skins: Seoul Dynasty. Gold3 Sup.",
      "accountType": "OW2 OG Account",
      "year": "2023",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 138.7,
      "priceType": "fixed",
      "nameChangeAvailable": true,
      "mythicPrisms": null,
      "credits": null,
      "competitivePoints": 1845,
      "rareSkins": [
        "Seoul Dynasty"
      ],
      "tags": [
        "OW2",
        "2023",
        "In Stock",
        "Name Change Available",
        "Battle Pass",
        "DPS Main",
        "Widow"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 30,
      "discord_id": null,
      "level": "860 in OW2",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🟢OG Account (2022)  <br>🔓SMS Verified • Warranty<br>⭐Endorsement Level 3 • Hide My Name Eligible • Genji Main(Lv. 80)<br>🎮Premium BP (Season 6, 11, 20, 2026-S1, S2) - Cyber Demon, Blazing Sunsetter, Bound Demon, A-7000 Wargod + 110 Mythic Prisms<br>✨Cardboard DVa, Kiniun Doom, Monkey Business Winston, Sakura Ball, Rugby Mauga, Cybervision Zarya, QIlin/Gladiator Queen JQ, Biohazard/Jade Totem Ram, Minotaur/Rosahardt Rein, Beekeeper/Beholder Sigma, Cardboard Bastion, Aviator Junk, Infinite Guard: 76, C-455 Sharpshooter Cassidy, Streetwear Hanzo, Formalwear Soj, Saint-Tropez/Sylvanas Widow, Archangel/Gold of Wealth/Street Runner/Polar Genji, Constable/Synthwave Tracer, Borealis/Retro Future Echo, Music Festival Pharah, Quciksilver/Aztec Sombra, Arch-Commandant Amari Ana, Bounty Hunter Bap, Cyber DJ/Disco Lucio, Bathmaster Zen, Oni/Visual Kei/Sakura Kiriko, Lifeguard/Royal Princess/OWL Guardian Mercy, Rosewood Moria<br>✨OW Contenders Zarya, OWCS Ashe, OWL Tracer, OW1 GZ Charge Bap",
      "weapons": "Golden: Genji<br>Hard Light: Reaper",
      "balance": "⏱ 703H • 4753G<br>💎110 Mythic Prisms<br>🏅2330 Legacy Comp Points",
      "rank": "Reset (S1 2026)",
      "nameChange": "✘",
      "screenshot": "https://imgur.com/a/NGVIKQe",
      "price": "$188.7",
      "title": "2022 · OW1 Account · 110 Mythic Prisms · $188.7",
      "summary": "OW1 Account. 110 Mythic Prisms. featured skins: Cyber Demon, OWCS, OWL. Reset (S1 2026).",
      "accountType": "OW1 Account",
      "year": "2022",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 188.7,
      "priceType": "fixed",
      "nameChangeAvailable": false,
      "mythicPrisms": 110,
      "credits": null,
      "competitivePoints": 2330,
      "rareSkins": [
        "Cyber Demon",
        "OWCS",
        "OWL"
      ],
      "tags": [
        "OW1",
        "OW2",
        "2022",
        "In Stock",
        "Mythic Prisms",
        "Golden Weapon",
        "Jade Weapon",
        "Hard Light",
        "Battle Pass",
        "League Skins",
        "Widow",
        "Hanzo"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 31,
      "discord_id": null,
      "level": "49+47 - OW1",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🏆OG OW1 Pre-Purchased Edition (2016)<br>✨Blizzcon Virtual Ticket 2016 • Noire Widowmaker Skin",
      "weapons": "",
      "balance": "🪙17420 Credits",
      "rank": "Reset (S1 2026)",
      "nameChange": "✓",
      "screenshot": "📸 View Skins",
      "price": "$198",
      "title": "2016 · OW1 Pre-Purchase Account · $198",
      "summary": "OW1 Pre-Purchase Account. 17,420 Credits. featured skins: Noire Widow, BlizzCon, Blizzcon. Reset (S1 2026).",
      "accountType": "OW1 Pre-Purchase Account",
      "year": "2016",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 198.0,
      "priceType": "fixed",
      "nameChangeAvailable": true,
      "mythicPrisms": null,
      "credits": 17420,
      "competitivePoints": null,
      "rareSkins": [
        "Noire Widow",
        "BlizzCon",
        "Blizzcon"
      ],
      "tags": [
        "OW1",
        "2016",
        "In Stock",
        "Credits",
        "Name Change Available",
        "BlizzCon",
        "Widow"
      ],
      "screenshotStatus": "missing_or_invalid"
    },
    {
      "id": 32,
      "discord_id": null,
      "level": "1154 - OW2",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🟢OG Account (2022)  <br>🔓SMS Verified • Warranty<br>⭐Endorsement Level 3 • DVa(Lv.63)/Moire(Lv.34)/Tracer(Lv.30)<br>🏅Top 500 • Hide My Name Eligible<br>🎮Premium Battle Pass (Season 10, 15, 16, 2026 S1) - Horang, Midnight Sun, Adventurer, Amaterasu<br>✨Turtle Ship/Dainty Cat DVa, Monkey Business Winston, Carved Orisa, Kabuki Ram, Cardboard/Heaven's Devil/Lich King Rein, Aviator Junk, Flower Child Mei, Captain Torb, Hashimoto/Cyber Dragon/Cyber Oni Hanzo, Cyber Detective/Infinite Admiral Soj, Heihu/Street Runner Genji, Sanguine Curse Ana, Flirty Flare Bap, Bathmaster Zen, Hashimoto/Visual Kei Kiriko, Blackswan/Cleric Lifewaver, Jingle Belle/Honey Bee Mercy, Rosewood Moria, Celestial/Cozy Juno",
      "weapons": "Golden: DVa, Winston, Sym, Tracer, Ana, Kiriko, Moira<br>Jade: Soldier: 76, Soj + 1 Any Gold/Jade/Galactic Weapon Skin<br>Nerf Gelfire Pro: Tracer",
      "balance": "⏱ 765H • 4795G<br>🪙2304 Credits<br>🏅3410 Legacy Comp Points",
      "rank": "Reset (S1 2026)<br>MMR: Silver - Gold<br>Stadium Comp Unlocked",
      "nameChange": "✓",
      "screenshot": "https://imgur.com/a/0P6F8q9",
      "price": "$210.7",
      "title": "2022 · OW2 OG Account · Golden Weapon · $210.7",
      "summary": "OW2 OG Account. 2,304 Credits. featured skins: Amaterasu. Reset (S1 2026) MMR: Silver - Gold Stadium Comp Unlocked.",
      "accountType": "OW2 OG Account",
      "year": "2022",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 210.7,
      "priceType": "fixed",
      "nameChangeAvailable": true,
      "mythicPrisms": null,
      "credits": 2304,
      "competitivePoints": 3410,
      "rareSkins": [
        "Amaterasu"
      ],
      "tags": [
        "OW2",
        "2022",
        "In Stock",
        "Credits",
        "Top 500",
        "Golden Weapon",
        "Jade Weapon",
        "Galactic Weapon",
        "Name Change Available",
        "Battle Pass",
        "Hanzo"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 33,
      "discord_id": null,
      "level": "902+509 - OW1 Stack Account",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🏆OG OW1 Legendary Edition (2016)<br>⭐Endorsement Level 4 • OW1 Season 1 Competitor<br>🏅Top 500 • Hide My Name Eligible • Zen • Kirko • Moria • Support Main<br>🎮Premium Battle Pass (Season 9, 19, 2026-S1, S2) - Spirit Keeper, Acient Caller + 160 Mythic Prisms<br>✨Funky/Kiniun Doom, Magepunk Mauga, Kaiju Hog, Poolside Rein, Junkbot Junk, Empress Mei, Streetwear/Cyber Oni Hanzo, Wild Tracker/Cyber Fiend Widow, Volcanic Genji, Eagle Warrior Reaper, Polar/Formalwear/Comic Book Tracer, Aset/Retro Future Echo, Midnight Camo Ana, Hermes Lucio, Pinocchio Zen, Jingle Belle/Beach Rescue/Poolside/Conjurer Mercy<br>✨LA Valiant Hog, OW1 Seoul Dynasty Mercy",
      "weapons": "Golden: Rein, Ana, Bap, Zen, Kiriko, Lucio, Lifewaver, Mercy, Moira, Brig, Illari<br>Jade: Mercy<br>+ Almost 1 Crimson Wolf Weapon + 4 Any Jade/Gold/Galactic Weapon Skins",
      "balance": "⏱ 1565H •9419G<br>💎160 Mythic Prisms<br>🪙50280 Credits<br>🏅13490 Legacy Comp Points | 2920 Comp Points",
      "rank": "Reset (S1 2026)<br>Gold Below",
      "nameChange": "✓",
      "screenshot": "https://imgur.com/a/MXkVQLh",
      "price": "$337.7",
      "title": "2016 · OW1 Legendary Account · 160 Mythic Prisms · $337.7",
      "summary": "OW1 Legendary Account. 160 Mythic Prisms. 50,280 Credits. featured skins: Seoul Dynasty. Reset (S1 2026) Gold Below.",
      "accountType": "OW1 Legendary Account",
      "year": "2016",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 337.7,
      "priceType": "fixed",
      "nameChangeAvailable": true,
      "mythicPrisms": 160,
      "credits": 50280,
      "competitivePoints": 2920,
      "rareSkins": [
        "Seoul Dynasty"
      ],
      "tags": [
        "OW1",
        "2016",
        "In Stock",
        "Mythic Prisms",
        "Credits",
        "Top 500",
        "Golden Weapon",
        "Jade Weapon",
        "Galactic Weapon",
        "Name Change Available",
        "Battle Pass",
        "Support Main",
        "Widow",
        "Hanzo"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 34,
      "discord_id": null,
      "level": "912+1114 - OW1 Stack Account",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🏆OG OW1 Legendary Edition (2016)<br>⭐Endorsement Level 5 • Tracer Main • Rare OWL Game Icon Collected<br>🏆OW1 - Season 4 Competitor •Top 500 Eligible • Hide My Name Eligible<br>🎮Premium BP Season (2, 5, 10, 13, 14, 15, 17, 20, 2026-S1) - Zeus, Anubis, Thor(Gilded), Pixiu, Steel Death, Adventurer + 200 Mythic Prisms<br>✨OWL: DVa/Orisa/Widow/Genji/Ana, OWCS Winston/Ball/Ram/Rein/Soj/Zen/Illari, OW1 Dallas Fuel Winston/Zarya, London Spitfire Zarya, OW1 Contenders Sigma/Soldier/Genji/Reaper/Lucio, OW2 Contenders Genji, Atlanta Reign Bap/Brig, OWC Zen, LA Gladiators Illari<br>✨Heist/Dainty Cat DVa, Kiniun Doom, Ugly Sweater Winston, Rugby Mauga, Dream Sheep/Rubber Ducky/Retro Future/Carved Orisa, Cybervision Zarya, Executioner/Gladiator Queen JQ, Jade Totem Ram,  Heaven's Devil/Fallen Knight Rein, Bronze Drake/Beholder/Odin Sigma, Lego Brick/Fire Engine/Pumpkin Bastion, Junkbot/Inferno/Aviator Junkrat, Empress Mei, Heist/Infinite Guard: 76/Golfer: 76 Soldier: 76, Infernal Witch/Celestial Sym, Lucky Cat/Merry Outlaw Ashe, Space Raider Cassidy, Cupid/Great Tengu/Koi Hanzo, Cyber Detective/Formalwear/Sea Soldier/Firefighter/Night Ops Soj, Medusa/Harlequin Widow, Divine Monkey/Volcanic/Polar Genji, Calavera/Fenrir Reaper, Comic Book/Constable/Synthwave Tracer, Ice Cream Venture, Automaton/Aset Echo, Nefertari/Nutcracker/Malachite/Devil Pharah, Marioneta/Demon Hunter Sombra, Blackbraid/Demon/Ultrawatch/Bastet/Midnight Camo Ana, Flirty Flare Bap, Octopus/Disco Lucio, Aang/Celestial/Bathmaster Zen, K-2000 Blademaster/Idunn/Visual Kei Kiriko, Lifeguarder/Cotton Candy Lifewaver, Rose Majesty/Ivory Rose/Honey Bee/Zombie Doctor/OWL Guardian Mercy, Plague Doctor/Rosewood Moira, Azure Drake/Pearlescent Brig, Eclipse Illari, Ember/Megepunk Juno",
      "weapons": "Golden: Winston, Zarya, Rein, Tracer, Ana, Bap, Cat, Kiriko, Zen<br>Galactic: Zen<br>Hard Light Weapon: Rein/Mercy<br>Los Muertos Weapon: Soldier: 76<br>Nerf Gelfire Pro: Tracer<br>+ 3 Any Weapon Skins",
      "balance": "⏱ 2174H • 12819G<br>💎200 Mythic Prisms<br>🪙10128 Credits • 599 Coins<br>🏅6612 Legacy Comp Points • 2600 Comp Points",
      "rank": "Diamond 4/5 All Roles<br>Stadium Comp Unlock",
      "nameChange": "✓",
      "screenshot": "https://imgur.com/a/YgIeDjo",
      "price": "$498.7",
      "title": "2016 · OW1 Legendary Account · 200 Mythic Prisms · $498.7",
      "summary": "OW1 Legendary Account. 200 Mythic Prisms. 10,128 Credits. featured skins: Lego Brick, Zeus, OWCS. Diamond 4/5 All Roles Stadium Comp Unlock.",
      "accountType": "OW1 Legendary Account",
      "year": "2016",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 498.7,
      "priceType": "fixed",
      "nameChangeAvailable": true,
      "mythicPrisms": 200,
      "credits": 10128,
      "competitivePoints": 2600,
      "rareSkins": [
        "Lego Brick",
        "Zeus",
        "OWCS",
        "OWL",
        "Dallas Fuel",
        "London Spitfire",
        "LA Gladiators"
      ],
      "tags": [
        "OW1",
        "OW2",
        "2016",
        "In Stock",
        "Mythic Prisms",
        "Credits",
        "Top 500",
        "Golden Weapon",
        "Jade Weapon",
        "Galactic Weapon",
        "Hard Light",
        "Name Change Available",
        "Battle Pass",
        "League Skins"
      ],
      "screenshotStatus": "valid"
    },
    {
      "id": 35,
      "discord_id": null,
      "level": "1527+239 Golden Border - OW1 Stack Account",
      "access": "BNET + Email  <br>OG Info • Invoice",
      "status": "🟢 In Stock",
      "highlights": "🏆OG OW1 Origins Edition (2016)<br>⭐Endorcement Level 4<br>🏆Top 500 Eligible • Hide Name Eligible • DPS • Sup Main<br>🏆OW1 TOP 500 Mutiple Seasons S16 17 18 19 20 21 22 23 24 25 27<br>🎮Premium Battle Pass (Season 1, 2, 16, 19, 2026-1, 2026-2)  - Zeus(Iridescent), Cyber Demon(Iridescent), Blazing Sunsette, Horang + 180 Mythic Prisms<br>✨Turtle Ship D.VA, Lifeguard Hog, Mob Boss & Poolside JQ, JADE Totem, Poolside Rein, Dragonfire & Lego Brick Bastion, Inferno Junk, Polar&Barista Soj, Emotional Reaper, Formalwear Tracer, Loki Sombra, Arch-Commandant Amari & Sanguine Curse & Lightbringer Ana, Z-3N Destroyer Zen, K-2000 Blademaster & Guangmu Tianwang & Visual Kei Kiriko, Zombie Doctor Mercy, Celestial & Rosewood Moria, Forget-me-not Juno<br>✨OWL:DVA/Ball/Hog/JQ/Sigma/Bastion/Mei/Ashe/Cassidy/Hanzo/Soj/Genji/Tracer/Echo/Pharah/Bap/Ana/Zen/Kiriko/Mercy/Brig<br>✨OWCS Wiston/Bap, Vancouver Titans Wiston/Torb/Hnazo, Huston Outlaws JQ, OW1 Seoul Dynasty Mei<br># Each Heros has more than 20+ Skins Collected and Almost all OW1 Items",
      "weapons": "Golden: Dva, Doom, Winston, Ball, Mauga, Orisa, Hog, Zarya, Ram, Sigam, Junk, Mei, Ashe, Cassidy, Hanzo, Widow, Genji, Reaper, Tracer, Echo, Pharah, Ana, Bap, Lucio, Mercy, Moira<br>Galactic: Orisa, Emre, Cassidy<br>Jade: Lucio",
      "balance": "⏱ 1641H • 9938G<br>💎160 Mythic Prisms<br>🪙24972 Credits<br>🏅1830 Comp Points",
      "rank": "Reset (S1 2026)",
      "nameChange": "✘",
      "screenshot": "https://imgur.com/a/LOZt3be",
      "price": "$627",
      "title": "2016 · OW1 Origins Account · 180 Mythic Prisms · $627",
      "summary": "OW1 Origins Account. 180 Mythic Prisms. 24,972 Credits. featured skins: Lego Brick, Cyber Demon, Zeus. Reset (S1 2026).",
      "accountType": "OW1 Origins Account",
      "year": "2016",
      "statusValue": "in_stock",
      "statusLabel": "🟢 In Stock",
      "priceValue": 627.0,
      "priceType": "fixed",
      "nameChangeAvailable": false,
      "mythicPrisms": 180,
      "credits": 24972,
      "competitivePoints": 1830,
      "rareSkins": [
        "Lego Brick",
        "Cyber Demon",
        "Zeus",
        "OWCS",
        "OWL",
        "Seoul Dynasty"
      ],
      "tags": [
        "OW1",
        "2016",
        "In Stock",
        "Mythic Prisms",
        "Credits",
        "Top 500",
        "Golden Weapon",
        "Jade Weapon",
        "Galactic Weapon",
        "Battle Pass",
        "League Skins",
        "DPS Main",
        "Support Main",
        "Widow"
      ],
      "screenshotStatus": "valid"
    }
  ]
};

const accounts = ACCOUNTS_DATA.accounts;

if (typeof window !== "undefined") {
  window.ACCOUNTS_B64 = ACCOUNTS_B64;
  window.ACCOUNTS_DATA = ACCOUNTS_DATA;
  window.accounts = accounts;
}

if (typeof globalThis !== "undefined") {
  globalThis.ACCOUNTS_B64 = ACCOUNTS_B64;
  globalThis.ACCOUNTS_DATA = ACCOUNTS_DATA;
  globalThis.accounts = accounts;
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = ACCOUNTS_DATA;
}
